# Generated by Django 5.2.9 on 2026-01-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_payment_transaction_id_alter_permission_id_and_more'),
    ]

    operations = [
        # Product indexes for load testing
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'stock'], name='api_product_category_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock'], name='api_product_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='api_product_created_at_idx'),
        ),


        # Cart indexes
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='api_cart_user_idx'),
        ),

        # CartItem indexes
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='api_cartitem_cart_product_idx'),
        ),

        # Order indexes
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='api_order_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='api_order_created_at_idx'),
        ),

        # OrderItem indexes
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='api_orderitem_order_idx'),
        ),

        # Payment indexes
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='api_payment_transaction_id_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='api_payment_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='api_payment_created_at_idx'),
        ),

        # Wishlist indexes
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'product'], name='api_wishlist_user_product_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['created_at'], name='api_wishlist_created_at_idx'),
        ),
    ]
