"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def env_bool(name, default="False"):
    return os.getenv(name, default).lower() in ("1", "true", "yes", "on")


def env_list(name, default=""):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]

def env_int(name, default):
    try:
        return int(os.getenv(name, str(default)))
    except ValueError:
        return default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "dev-insecure-secret")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", "False")

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "localhost,127.0.0.1,[::1]")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'drf_spectacular',
    "rest_framework_simplejwt",
    'corsheaders',
    'django_filters',
    


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'data_test'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', '123456'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'CONN_MAX_AGE': env_int('DB_CONN_MAX_AGE', 300),  # Longer connection lifetime for load tests
            'CONN_HEALTH_CHECKS': env_bool('DB_CONN_HEALTH_CHECKS', 'True'),
            'OPTIONS': {
                'connect_timeout': env_int('DB_CONNECT_TIMEOUT', 10),  # Longer timeout for load tests
                'keepalives': 1,  # Enable TCP keepalives
                'keepalives_idle': 30,  # TCP keepalive idle time
                'keepalives_interval': 10,  # TCP keepalive interval
                'keepalives_count': 5,  # TCP keepalive count
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

API_CACHE_TTL = env_int("API_CACHE_TTL", 0)

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "tmdt-cache",
    }
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    "EXCEPTION_HANDLER": "api.utils.exception_handler.custom_exception_handler",
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
    # Enable pagination globally so list endpoints honor `page` and `page_size` query params
    'DEFAULT_PAGINATION_CLASS': 'api.pagination.StandardResultsSetPagination',
    'DEFAULT_THROTTLE_RATES': {
        'login': os.getenv('THROTTLE_RATE_LOGIN', '10000/min'),  # Much higher for load testing
        'cart': os.getenv('THROTTLE_RATE_CART', '50000/min'),   # Much higher for load testing
        'order': os.getenv('THROTTLE_RATE_ORDER', '10000/min'), # Much higher for load testing
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'TMDT API',
    'DESCRIPTION': 'OpenAPI schema for TMDT backend',
    'VERSION': '1.0.0',
}

# Security for Swagger / OpenAPI: enable Bearer JWT in the UI
SPECTACULAR_SETTINGS.setdefault('COMPONENTS', {})
SPECTACULAR_SETTINGS['COMPONENTS'].setdefault('securitySchemes', {})
SPECTACULAR_SETTINGS['COMPONENTS']['securitySchemes']['BearerAuth'] = {
    'type': 'http',
    'scheme': 'bearer',
    'bearerFormat': 'JWT',
}

# Apply BearerAuth globally so the Swagger UI shows Authorize button
SPECTACULAR_SETTINGS.setdefault('SECURITY', [{'BearerAuth': []}])

PAYMENT_WEBHOOK_SECRET = os.getenv("PAYMENT_WEBHOOK_SECRET", "dev-webhook-secret")
try:
    PAYMENT_WEBHOOK_TOLERANCE_SECONDS = int(
        os.getenv("PAYMENT_WEBHOOK_TOLERANCE_SECONDS", "300")
    )
except ValueError:
    PAYMENT_WEBHOOK_TOLERANCE_SECONDS = 300

# High concurrency optimizations for load testing
DATABASE_ROUTERS = []

# Disable query logging in production/load testing
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',  # Only show warnings/errors, not every query
        },
    },
}

# Optimized database settings for load testing
if os.getenv('LOAD_TEST_MODE', 'false').lower() == 'true':
    # For load testing, use persistent connections instead of pooling
    # Remove any pooling options that might conflict
    if 'pool' in DATABASES['default']['OPTIONS']:
        del DATABASES['default']['OPTIONS']['pool']

    # Optimize connection settings for high concurrency
    DATABASES['default']['CONN_MAX_AGE'] = 600  # Even longer for load tests
    DATABASES['default']['CONN_HEALTH_CHECKS'] = True
    DATABASES['default']['OPTIONS'].update({
        'connect_timeout': 15,  # Longer timeout
        'keepalives': 1,
        'keepalives_idle': 60,    # Longer keepalive
        'keepalives_interval': 15, # Longer interval
        'keepalives_count': 10,    # More retries
    })

# Optimize Django for high concurrency
USE_TZ = True
SECRET_KEY = os.getenv("SECRET_KEY", "dev-insecure-secret-for-load-testing")

# Cache settings for load testing
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "tmdt-cache",
        "OPTIONS": {
            "MAX_ENTRIES": 10000,  # Higher cache capacity for load tests
        }
    }
}

# Session settings for load testing
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

# Optimize REST Framework for load testing
REST_FRAMEWORK.update({
    'DEFAULT_RENDERER_CLASSES': (
        "rest_framework.renderers.JSONRenderer",
    ),
    'UNAUTHENTICATED_USER': None,
    'DEFAULT_PERMISSION_CLASSES': (),
})

# Disable debug toolbar and other development middleware during load tests
if os.getenv('LOAD_TEST_MODE', 'false').lower() == 'true':
    DEBUG = False
    MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'corsheaders.middleware.CorsMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ]
